# Generated by Django 5.2.10 on 2026-02-09 08:40

import pkg.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Kullanıcının tüm izinlere sahip olduğunu belirtir.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=pkg.utils.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField(default=False, help_text='Kullanıcının admin ekranına erişim izni var mı?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('roles', models.ManyToManyField(blank=True, help_text='Kullanıcının ait olduğu roller.', related_name='user_set', related_query_name='user', to='authorization.role', verbose_name='roller')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Bu kullanıcıya özel yetkiler.', related_name='user_set', related_query_name='user', to='authorization.permission', verbose_name='kullanıcı yetkileri')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': '01.1 - Kullanıcılar',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
