# Generated by Django 5.2.10 on 2026-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('codename', models.CharField(max_length=255, unique=True, verbose_name='Kod')),
                ('name', models.JSONField(help_text='Farklı dillerde yetki ismi. Örn: {"en": "Can View", "tr": "Görüntüleyebilir"}', verbose_name='Yetki Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Yetki',
                'verbose_name_plural': '02.1 - Yetkiler',
                'db_table': 'permissions',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.JSONField(help_text='Rol ismi farklı dillerde. Örn: {"en": "Admin", "tr": "Yönetici"}', verbose_name='İsim')),
                ('codename', models.CharField(max_length=150, unique=True, verbose_name='Kod')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authorization.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': '02.0 - Roller',
                'db_table': 'roles',
                'ordering': ['codename'],
            },
        ),
    ]
